apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-app
  labels:
    app: kub-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kub-app
  template:
    metadata:
      labels:
        app: kub-app
    spec:
      containers:
        - name: kub-app
          image: hell7/kub-app:v1
          ports:
            - containerPort: 3000   # âœ… Your app listens here
      imagePullSecrets:
        - name: regcred

